import type { Metadata } from "next";
import { Electrolize, VT323 } from "next/font/google";
import "./globals.css";

import { WindowElementsProvider } from '@/context/windowElementsContext';
import { ShowHelpProvider } from "@/context/helpContext";
import { isMobileType } from "@/utils/deviceCheck";
import { TranslateProvider } from "./context/translateContext";

const custom = Electrolize({
  variable: "--font-custom",
  weight: '400',
  subsets: ["latin"],
});

const musicPlayer = VT323({
  variable: "--font-music-player",
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Juan Pablo Lepore's CV",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = await isMobileType();

  return (
    <html lang="en">
      <body
        className={`${custom.variable} ${musicPlayer.variable} antialiased`}
      >
        <TranslateProvider>
          <WindowElementsProvider isMobile={isMobile}>
            <ShowHelpProvider>
              {children}
            </ShowHelpProvider>
          </WindowElementsProvider>
        </TranslateProvider>
      </body>
    </html>
  );
}
