import type { Metadata } from "next";
import { Electrolize } from "next/font/google";
import "./globals.css";

import { WindowElementsProvider } from '@/context/windowElementsContext';
import { ShowHelpProvider } from "@/context/helpContext";

const custom = Electrolize({
  variable: "--font-custom",
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Juan Pablo Lepore's CV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${custom.variable} antialiased`}
      >
        <WindowElementsProvider>
          <ShowHelpProvider>
            {children}
          </ShowHelpProvider>
        </WindowElementsProvider>
      </body>
    </html>
  );
}
